path fix

diff --git a/.github/workflows/backend-frontend.yml b/.github/workflows/backend-frontend.yml
--- a/.github/workflows/backend-frontend.yml
+++ b/.github/workflows/backend-frontend.yml
@@ -69,8 +69,19 @@ jobs:
         run: |
           cd frontend
           npx http-server -p 8000 &
-          sleep 10
-          curl http://localhost:8000
+          echo "Waiting for frontend to be available..."
+          attempt_counter=0
+          max_attempts=10
+          until curl --output /dev/null --silent --head --fail http://localhost:8000; do
+            if [ ${attempt_counter} -eq ${max_attempts} ]; then
+              echo "Frontend server failed to start"
+              exit 1
+            fi
+            printf '.'
+            attempt_counter=$((attempt_counter+1))
+            sleep 3
+          done
+          echo "Frontend is up!"
 
       - name: Run Frontend Tests
         run: |
